use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :construtora_lc_hiert, ConstrutoraLcHiertWeb.Endpoint,
  http: [:inet6, port: System.get_env("PORT")],
  url: [scheme: "https", host: "construtoralchiert.com.br", port: 443],
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  secret_key_base: System.get_env("SECRET_KEY_BASE"),
  cache_static_manifest: "priv/static/cache_manifest.json",
  live_view: [signing_salt: System.get_env("LIVE_VIEW_SECRET_KEY")],
  check_origin: ["//construtoralchiert.com.br", "//qa-construtora-lc-hiert.herokuapp.com"]

# Configure your database
config :construtora_lc_hiert, ConstrutoraLcHiert.Repo,
  url: System.get_env("DATABASE_URL"),
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10"),
  ssl: true

# Guardian - Authentication configs
config :construtora_lc_hiert, ConstrutoraLcHiert.Authentication.Guardian,
  issuer: "construtora_lc_hiert",
  secret_key: System.get_env("GUARDIAN_SECRET_KEY")

# Email configurations
config :construtora_lc_hiert, ConstrutoraLcHiert.Mailer,
  adapter: Bamboo.SMTPAdapter,
  server: "smtp.sendgrid.net",
  port: 587,
  username: "apikey",
  password: System.get_env("SENDGRID_API_KEY"),
  tls: :always

# ARC S3 Storage
config :arc,
  storage: Arc.Storage.S3,
  bucket: System.get_env("S3_BUCKET")

config :ex_aws,
  access_key_id: System.get_env("AWS_ACCESS_KEY_ID"),
  secret_access_key: System.get_env("AWS_SECRET_ACCESS_KEY")

# Do not print debug messages in production
config :logger, level: :info
